version: 2.1

orbs:
    clojure: lifecheq/clojure@0.0.1

jobs:

  util_job:
    description: |
      Running utility commands/checks (linter etc.)
      Always uses Java11 and Clojure 1.10
    parameters:
      steps:
        type: steps
    executor: clojure/openjdk11
    environment:
      VERSION: "1.10"
    steps:
      - checkout
      - run:
          name : Install make
          command: |
            sudo apt-get install make
      - clojure/with_cache:
          cache_version: "1.10"
          steps: << parameters.steps >>


  test_code:
    description: |
      Run tests against given version of JDK and Clojure
    parameters:
      jdk_version:
        description: Version of JDK to test against
        type: string
      clojure_version:
        description: Version of Clojure to test against
        type: string
    executor: clojure/<< parameters.jdk_version >>
    environment:
      VERSION: << parameters.clojure_version >>
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run:
                name : Install make
                command: |
                  sudo apt-get install make
            - run:
                name: Running tests
                command: make test
            - store_test_results:
                path: test-results

# The ci-test-matrix does the following:
#
# - run tests against the target matrix
#   - Java 8 and 11
#   - Clojure 1.7, 1.8, 1.9, 1.10, master
# - linter, eastwood and cljfmt
# - verifies cljdoc config
# - runs code coverage report

workflows:
  version: 2.1
  ci-test-matrix:
    jobs:
      #- test_code:
      #     name: Java 8, Clojure 1.7
      #     clojure_version: "1.7"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 8, Clojure 1.8
      #     clojure_version: "1.8"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 8, Clojure 1.9
      #     clojure_version: "1.9"
      #     jdk_version: openjdk8
      - test_code:
          name: Java 8, Clojure 1.10
          clojure_version: "1.10"
          jdk_version: openjdk8
      # - test_code:
      #     name: Java 8, Clojure master
      #     clojure_version: "master"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 11, Clojure 1.7
      #     clojure_version: "1.7"
      #     jdk_version: openjdk11
      # - test_code:
      #     name: Java 11, Clojure 1.8
      #     clojure_version: "1.8"
      #     jdk_version: openjdk11
      # - test_code:
      #     name: Java 11, Clojure 1.9
      #     clojure_version: "1.9"
      #     jdk_version: openjdk11
      - test_code:
          name: Java 11, Clojure 1.10
          clojure_version: "1.10"
          jdk_version: openjdk11
      # - test_code:
      #     name: Java 11, Clojure master
      #     clojure_version: "master"
      #     jdk_version: openjdk11
      - util_job:
          name: Code Linting
          steps:
            - run:
                name: Running Eastwood
                command: |
                  make eastwood
            - run:
                name: Running cljfmt
                command: |
                  make cljfmt
      # - util_job:
      #     name: Checking Cljdoc
      #     steps:
      #       - run:
      #           name: Verifying Cljdoc
      #           command: |
      #             make verify_cljdoc
