version: 2.1

orbs:
    clojure: lifecheq/clojure@dev:first

test_steps: &test_steps
  steps:
    - run:
        name: Running tests
        command: make test
    - store_test_results:
        path: test-results

# The ci-test-matrix does the following:
#
# - run tests against the target matrix
#   - Java 8 and 11
#   - Clojure 1.7, 1.8, 1.9, 1.10, master
# - linter, eastwood and cljfmt
# - verifies cljdoc config
# - runs code coverage report

workflows:
  version: 2.1
  ci-test-matrix:
    jobs:
      #- test_code:
      #     name: Java 8, Clojure 1.7
      #     clojure_version: "1.7"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 8, Clojure 1.8
      #     clojure_version: "1.8"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 8, Clojure 1.9
      #     clojure_version: "1.9"
      #     jdk_version: openjdk8
      - clojure/run_test:
          name: Java 8, Clojure 1.10
          clojure_version: "1.10"
          jdk_version: openjdk8
          <<: *test_steps
      # - test_code:
      #     name: Java 8, Clojure master
      #     clojure_version: "master"
      #     jdk_version: openjdk8
      # - test_code:
      #     name: Java 11, Clojure 1.7
      #     clojure_version: "1.7"
      #     jdk_version: openjdk11
      # - test_code:
      #     name: Java 11, Clojure 1.8
      #     clojure_version: "1.8"
      #     jdk_version: openjdk11
      # - test_code:
      #     name: Java 11, Clojure 1.9
      #     clojure_version: "1.9"
      #     jdk_version: openjdk11
      - clojure/run_test:
          name: Java 11, Clojure 1.10
          clojure_version: "1.10"
          jdk_version: openjdk11
          <<: *test_steps
      # - test_code:
      #     name: Java 11, Clojure master
      #     clojure_version: "master"
      #     jdk_version: openjdk11
      - clojure/run_test:
          name: Code Linting
          steps:
            - run:
                name: Running Eastwood
                command: |
                  make eastwood
            - run:
                name: Running cljfmt
                command: |
                  make cljfmt
      # - util_job:
      #     name: Checking Cljdoc
      #     steps:
      #       - run:
      #           name: Verifying Cljdoc
      #           command: |
      #             make verify_cljdoc
